<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            font-size: 10px;
            line-height: 1.3;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
            font-size: 9px;
        }

        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }

        .header-table td {
            border: none;
            padding: 10px;
            border: 1px solid #ddd;
            background-color: #fff;
            page-break-inside: avoid;
        }

        .logo {
            text-align: center;
            vertical-align: top;
        }

        .logo img {
            max-width: 80px;
            margin-bottom: 3px;
        }

        h3 {
            font-size: 11px;
            border-bottom: 1px solid #007bff;
            margin-bottom: 8px;
            padding-bottom: 3px;
        }

        .footer {
            text-align: center;
            font-size: 8px;
            color: #555;
            margin-top: 10px;
        }

        .bank-details {
            text-align: left;
            font-size: 8px;
            color: #333;
        }

        tr {
            page-break-inside: avoid;
        }
    </style>
</head>

<body>

    <!-- Table Layout -->
    <table class="header-table">
        <tr>
            <!-- Company Information -->
            <td width="40%">
                <h4 style="color: #007bff;">Company Information</h4>
                <p><strong>Company Name:</strong> HOLISTIC LEGACY ACCOUNTING</p>
                <p><strong>Address:</strong> {{ $invoiceData['companyAddress'] ?? 'Company Address' }}</p>
                <p><strong>Phone:</strong> {{ $invoiceData['companyPhone'] ?? 'N/A' }}</p>
                <p><strong>Email:</strong> {{ $invoiceData['companyEmail'] ?? 'N/A' }}</p>
            </td>

            <!-- Logo -->
            <td width="20%" class="logo">
                <img src="{{ public_path('assets/admin/img/logo-def.png') }}" alt="Company Logo">
            </td>

            <!-- Invoice Information -->
            <td width="40%">
                <h2 style="color: #e74c3c;">Invoice</h2>
                <p><strong>Invoice Number:</strong> {{ $invoiceData['invoiceNumber'] }}</p>
                <p><strong>TRN NO.</strong> 104668704000003</p>
                <p><strong>Invoice Date:</strong> {{ $invoiceData['date'] }}</p>
                <p><strong>Generated By:</strong> {{ $invoiceData['created']['name'] ?? 'N/A' }}</p>
                <p><strong>Payment By:</strong> {{ $invoiceData['payment_method'] }}</p>
            </td>
        </tr>
    </table>

    <!-- Customer Information -->
    <h3>Customer Information</h3>
    <table>
        <tr>
            <td><strong>Name:</strong></td>
            <td>{{ $invoiceData['customer']['first_name'] ?? 'N/A' }}
                {{ $invoiceData['customer']['last_name'] ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Business:</strong></td>
            <td>{{ $invoiceData['customer']['business_name'] ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Phone:</strong></td>
            <td>{{ $invoiceData['customer']['phone_number'] ?? 'N/A' }}</td>
        </tr>
        <tr>
            <td><strong>Email:</strong></td>
            <td>{{ $invoiceData['customer']['email'] ?? 'N/A' }}</td>
        </tr>
    </table>

    <!-- Service Details -->
    <h3>Service</h3>
    <table>
        <thead>
            <tr>
                <th>Service Name</th>
                <th>Price (AED)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoiceData['services'] as $serviceItem)
                <tr>
                    <td> {{ $loop->iteration }}. {{ $serviceItem['name'] ?? 'N/A' }}</td>
                    <td>AED {{ number_format($serviceItem['price'] ?? 0, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Total Summary -->
    <h3>Total Summary</h3>
    <table>
        <tr>
            <th>VAT ({{ $invoiceData['customer']['vat_value'] ?? 0 }}%)</th>
            <td>AED {{ number_format($invoiceData['vatAmount'], 2) }}</td>
        </tr>
        <tr>
            <th>Total Amount</th>
            <td>AED {{ number_format($invoiceData['totalAmount'], 2) }}</td>
        </tr>
    </table>

    <!-- Footer -->
    <table>
        <tr>
            <td class="bank-details">
                <strong>Bank Details:</strong><br>
                Account Holder Name: HOLISTIC LEGACY ACCOUNTING S.P.S L.L.C<br>
                Bank Name: Abu Dhabi Islamic Bank (ADIB)<br>
                Account No: 19326413<br>
                IBAN: AE720500000000019326413<br>
                Swift Code: ABDIAEAD
            </td>
            <td class="footer">
                &copy; {{ date('Y') }} HOLISTIC LEGACY ACCOUNTING S.P.S L.L.C All Rights Reserved.
            </td>
        </tr>
    </table>

</body>

</html>
