<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice & Receipt</title>

</head>

<body>


    <div class="invoice-container">
        <!-- Invoice Section -->
        <div class="container">
            <div class="header">
                <div class="header-left">
                    <h4>Customer Information</h4>
                    <p><strong>Name:</strong> {{ $customer->first_name }} {{ $customer->last_name }}</p>
                    <p><strong>Business:</strong> {{ $customer->business_name }}</p>
                    <p><strong>Phone:</strong> {{ $customer->phone_number }}</p>
                    <p><strong>Email:</strong> {{ $customer->email }}</p>
                    <p><strong>TRN:</strong> {{ $customer->tax_id }}</p>

                </div>
                <div class="header-center">
                    <img src="{{ asset('assets/admin/img/logo-def.png') }}" alt="Company Logo">
                    <p>{{ $companyAddress }}</p>
                    <p>Phone: {{ $companyPhone }}</p>
                    <p>Email: {{ $companyEmail }}</p>
                </div>
                <div class="header-right">
                    <h2>Tax Invoice</h2>
                    <p><strong>Invoice Number:</strong> {{ $invoiceNumber }}</p>
                    <p><strong>TRN NO.</strong> 104668704000003</p>
                    <p><strong>Invoice Date:</strong> {{ $date }}</p>
                    <p><strong>Generated By:</strong> {{ $created->name }}</p>
                    <p><strong>Payment By:</strong> {{ $payment_method }}</p>
                </div>
            </div>

            <h3>Service</h3>
            <table>
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Price (AED)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($services as $serviceItem)
                        <tr>
                            <td> {{ $loop->iteration }}. {{ $serviceItem['name'] }}</td>
                            <td>AED {{ number_format($serviceItem['price'], 2) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <h3>Total Summary</h3>
            <table>
                <tr>
                    <th>VAT ({{ $customer->vat_value }}%)</th>
                    <td>AED {{ number_format($vatAmount, 2) }}</td>
                </tr>
                <tr>
                    <th>Total Amount</th>
                    <td>AED {{ number_format($customer->price + $vatAmount, 2) }}</td>
                </tr>
            </table>

            <div class="signed-by">
                <div class="signature-box">Customer Signature</div>
                <div class="signature-box">Authorized Signature</div>
            </div>

            <div class="footer">
                <div class="bank-details">
                    <strong>Bank Details:</strong><br>
                    Account Holder Name: Holistic Legacy Accounting SPS LLC<br>
                    Bank Name: Abu Dhabi Islamic Bank (ADIB)<br>
                    Account No: 19326413<br>
                    IBAN: AE720500000000019326413<br>
                    Swift Code: ABDIAEAD
                </div>
                <div>&copy; {{ date('Y') }} HOLISTIC LEGACY ACCOUNTING S.P.S L.L.C All Rights Reserved.</div>
            </div>
        </div>

        <!-- Receipt Section -->
        <div class="container Receipt">
            <div class="header">
                <div class="header-left">
                    <h4>Customer Information</h4>
                    <p><strong>Name:</strong> {{ $customer->first_name }} {{ $customer->last_name }}</p>
                    <p><strong>Business:</strong> {{ $customer->business_name }}</p>
                    <p><strong>Phone:</strong> {{ $customer->phone_number }}</p>
                    <p><strong>Email:</strong> {{ $customer->email }}</p>
                    <p><strong>TRN:</strong> {{ $customer->tax_id }}</p>

                </div>
                <div class="header-center">
                    {{-- <img src="{{ asset('assets/admin/img/logo-def.png') }}" alt="Company Logo"> --}}
                    <img src="https://uaedesk.com/storage/favicon (2).PNG" alt="Company Logo">

                    <p>{{ $companyAddress }}</p>
                    <p>Phone: {{ $companyPhone }}</p>
                    <p>Email: {{ $companyEmail }}</p>
                </div>
                <div class="header-right">
                    <h2 style="color: #e74c3c;">Receipt</h2>
                    <p><strong>Receipt Number:</strong> {{ $receiptNumber }}</p>
                    <p><strong>Receipt Date:</strong> {{ $receiptDate }}</p>
                    <p><strong>Generated By:</strong> {{ $created->name }}</p>
                    <p><strong>Payment By:</strong> {{ $payment_method }}

                </div>
            </div>


            <h3>Payment Details</h3>
            <table>
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>Amount (AED)</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($services as $serviceItem)
                        <tr>
                            <td> {{ $loop->iteration }}. {{ $serviceItem['name'] }}</td>
                            <td>AED {{ number_format($serviceItem['price'], 2) }}</td>
                        </tr>
                    @endforeach

                </tbody>
            </table>

            <h3>Total Paid</h3>
            <table>
                <tr>
                    <th>Base Amount</th>
                    <td>AED {{ number_format($customer->price, 2) }}</td>
                </tr>
                <tr>
                    <th>VAT (%)</th>
                    <td>AED {{ number_format($vatAmount, 2) }}</td>
                </tr>
                <tr>
                    <th>Total Paid</th>
                    <td>AED {{ number_format($customer->price + $vatAmount, 2) }}</td>
                </tr>
            </table>
            <div class="signed-by">
                <div class="signature-box">Customer Signature</div>
                <div class="signature-box">Authorized Signature</div>
            </div>
            <div class="footer" style="text-align: center; display: block;">&copy; {{ date('Y') }} HOLISTIC LEGACY
                ACCOUNTING S.P.S L.L.C All Rights Reserved.
            </div>
        </div>
    </div>
    <div class="print-btn-container ">
        <button class="btn print-btn" onclick="window.print()">Print both</button>

        <a href="{{ route('print-invoice', $customer->id) }}" target="_blank" class="btn print-btn"> View
            Invoice</a>
        <a href="{{ route('print-receipt', $customer->id) }}" target="_blank" class="btn print-btn"> View Receipt</a>

    </div>
</body>

</html>
